### PR TITLE
Set color.ui=never when running git commands

### LINKED ISSUE #4717: Panic when 'git branch' command outputs in color
### Steps to reproduce

MacBook Pro running Sequioa 15.4. It's a pretty fresh machine, so I was installing 'git town' on it.
When I run 'git town config setup -v' I get an error:

```
panic: "\x1b[m" is not a valid Git SHA
```

This happens both with Apple git (pre-installed) as well as with brew installed git. I think it has to do with the 'git branch' command outputting in color -- see attached screenshot. Thanks!!

Image

### Command output

```shell
(verbose) git stash list

(verbose) git branch -vva --sort=refname
* master                          1adfd272aaae76850789b6106354492c1f05d3cb [origin/master] Merge pull request #64 from Mikrz/stop_ignoring_environment
  remotes/origin/HEAD             -> origin/master
  remotes/origin/completion       4e52e2edf8497cd8c977417d7f460f6229f2f829 Add zsh completion for fzm
  remotes/origin/demo             fe035ddd4c244193527c2d8c454c9290c3ae575a Add new demo
  remotes/origin/master           1adfd272aaae76850789b6106354492c1f05d3cb Merge pull request #64 from Mikrz/stop_ignoring_environment
  remotes/origin/revert-41-master 3168e9c9b23d2f0543dba94334718d98b9fe5ae0 Revert "added possibilty to paste a directory"
panic: "\x1b[m" is not a valid Git SHA

goroutine 1 [running]:
github.com/git-town/git-town/v18/internal/git/gitdomain.NewSHA(...)
	github.com/git-town/git-town/v18/internal/git/gitdomain/sha.go:16
github.com/git-town/git-town/v18/internal/git.ParseVerboseBranchesOutput({0x1400021e900, 0x2c1})
	github.com/git-town/git-town/v18/internal/git/commands.go:959 +0xa74
github.com/git-town/git-town/v18/internal/git.(*Commands).BranchesSnapshot(0x14000235a80, {0x104af3130, 0x14000130798})
	github.com/git-town/git-town/v18/internal/git/commands.go:116 +0x1d0
github.com/git-town/git-town/v18/internal/execute.LoadRepoSnapshot({{0x104af4970, 0x14000130798}, {0x1400010eab0}, {0x140002113b0, 0x140002116b0}, {0x140001307b0}, 0x0, {0x14000130768}, {0x104af1460, 0x14000211b00}, ...})
	github.com/git-town/git-town/v18/internal/execute/load_repo_snapshot.go:63 +0x29c
github.com/git-town/git-town/v18/internal/cmd/config.loadSetupData({{0x104af4970, 0x14000130798}, {0x1400010eab0}, {0x140002113b0, 0x140002116b0}, {0x14000130768}, {0x104af1460, 0x14000211b00}, {0x14000211230, 0x140001146b0}, ...}, ...)
	github.com/git-town/git-town/v18/internal/cmd/config/setup.go:250 +0x1b4
github.com/git-town/git-town/v18/internal/cmd/config.executeConfigSetup(0x1)
	github.com/git-town/git-town/v18/internal/cmd/config/setup.go:65 +0x114
github.com/git-town/git-town/v18/internal/cmd/config.SetupCommand.func1(0x1400013c900?, {0x14000114650?, 0x4?, 0x1048ab19e?})
	github.com/git-town/git-town/v18/internal/cmd/config/setup.go:38 +0x40
github.com/spf13/cobra.(*Command).execute(0x14000209b08, {0x14000114620, 0x1, 0x1})
	github.com/spf13/cobra@v1.9.1/command.go:1015 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14000208008)
	github.com/spf13/cobra@v1.9.1/command.go:1148 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/git-town/git-town/v18/internal/cmd.Execute()
	github.com/git-town/git-town/v18/internal/cmd/doc.go:47 +0x3fc
main.main()
	github.com/git-town/git-town/v18/main.go:18 +0x28
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stephenwade**
Fixes #4717.

### CODE REVIEW

**Comment by stephenwade** [comment]
With https://github.com/git-town/git-town/pull/4736, I verified that all the tests now pass if the user has `color.ui` set to `always`.

File: internal/git/commands.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func (self *Commands) BranchInSyncWithTracking(querier gitdomain.Querier, branch
 }
 
 func (self *Commands) BranchesSnapshot(querier gitdomain.Querier) (gitdomain.BranchesSnapshot, error) {
-	output, err := querier.QueryWithEnv([]string{`GIT_CONFIG_PARAMETERS='core.abbrev=40'`}, "git", "branch", "-vva", "--sort=refname")
+	output, err := querier.Query("git", "-c", "core.abbrev=40", "branch", "-vva", "--sort=refname")
```
Comment (kevgo) [inline internal/git/commands.go:92]: Great idea. I hadn't fully grokked this syntax before.

**Review by kevgo — APPROVED** [review]
Thanks for fixing this, very good solution! :rocket:
