### PR TITLE
Fix output of git ship

### LINKED ISSUE #1587: wrong output for "git ship" with code hosting driver
expected output:

```
GitHub API: Merging PR #56
```

actual output:

```
GitHub API: Merging PR #%d 56
```

### PR DESCRIPTION
**Pull request by kevgo**
resolves #1587

### CODE REVIEW

File: src/drivers/github.go [hunk 1]
```diff
@@ -126,7 +126,7 @@ func (d *githubCodeHostingDriver) mergePullRequest(options MergePullRequestOptio
 		return "", fmt.Errorf("cannot merge via Github since there is no pull request")
 	}
 	if options.LogRequests {
-		d.log("GitHub API: Merging PR #%d", options.PullRequestNumber)
+		d.log("GitHub API: Merging PR", options.PullRequestNumber)
```
Comment (charlierudolph) [inline src/drivers/github.go:129]: From the related issue,  i don't think this would match the expected output.

Expected: `GitHub API: Merging PR #56`
Logically what I think this will print: `GitHub API: Merging PR 56`

Comment (kevgo) [reply src/drivers/github.go:129]: You are right. Addressing in https://github.com/git-town/git-town/pull/1603
