### PR TITLE
[internal/cmd] merge should update child proposal targets + change order of operations to close proposal

### LINKED ISSUE #5701: git-town merge behaves in an unexpected way when merging a branch in the middle of stack
### Steps to reproduce

Say you have the following branches

```zsh
$ git-town branch
main
    branch-a
 *      branch-b
               branch-c
```

Each of these 3 branches has an existing proposal (whether in draft or ready to review). if you run `git-town merge` from branch-b, the cli does the correct thing and merges to branch-a but never updates the target for branch-c's proposal. 

Github deletes branch-b and because that branch no longer exists branch-c's proposal is auto-closed.

This came up in manual testing for proposal stack lineage

### Command output

```shell
[branch-b] git fetch --prune --tags

[branch-b] git checkout branch-a
Switched to branch 'branch-a'
Your branch is up to date with 'origin/branch-a'.

[branch-a] git reset --hard f4038610336e10825b719a43e974fba2ad3721f2
HEAD is now at f403861 Merge branch 'branch-a' into branch-b

[branch-a] git branch -D branch-b
Deleted branch branch-b (was f403861).

[branch-a] git push --force-with-lease --force-if-includes
remote:
remote: GitHub found 57 vulnerabilities on yaadata/ti-prep's default branch (3 critical, 20 high, 27 moderate, 7 low). To find out more, visit:
remote:      https://github.com/yaadata/ti-prep/security/dependabot
remote:
To github.com:yaadata/ti-prep.git
   4e13985..f403861  branch-a -> branch-a

[branch-a] git push origin :branch-b
remote:
remote: GitHub found 57 vulnerabilities on yaadata/ti-prep's default branch (3 critical, 20 high, 27 moderate, 7 low). To find out more, visit:
remote:      https://github.com/yaadata/ti-prep/security/dependabot
remote:
To github.com:yaadata/ti-prep.git
 - [deleted]         branch-b


deleted branch "branch-b"
```

### Additional information

We should update the proposal targets of all child proposals prior to merging, similar to ship

### PR DESCRIPTION
**Pull request by yaadata**
Resolves

#5701
#5702 

-------------------------
 - main
   - https://github.com/git-town/git-town/pull/5756 :point_left:

<sup>[Stack](https://www.git-town.com/how-to/github-actions-breadcrumb.html) generated by [Git Town](https://github.com/git-town/git-town)</sup>

### CODE REVIEW

File: internal/cmd/merge.go [hunk 1]
```diff
@@ -287,40 +290,57 @@ func determineMergeData(repo execute.OpenRepoResult) (data mergeData, flow confi
...
 		prog.Value.Add(&opcodes.BranchCurrentResetToSHA{SetToSHA: data.initialBranchSHA})
 	}
+	for _, child := range data.childBranches {
+		prog.Value.Add(&opcodes.LineageParentSetToGrandParent{Branch: child})
+	}
 	prog.Value.Add(&opcodes.LineageParentRemove{
 		Branch: data.initialBranch,
 	})
+	initialTrackingBranch, initialHasTrackingBranch := data.initialBranchInfo.RemoteName.Get()
+	if initialHasTrackingBranch && repo.IsOffline.IsOnline() {
```
Comment (yaadata) [inline internal/cmd/merge.go:344]: if you delete the remote branch before updating the parent branch, this will close the related proposal where the base is the branch being merged and the target is the parent branch

File: internal/cmd/merge.go [hunk 2]
```diff
@@ -287,40 +290,57 @@ func determineMergeData(repo execute.OpenRepoResult) (data mergeData, flow confi
 	}
 	initialBranchType := validatedConfig.BranchType(initialBranch)
 	parentBranchType := validatedConfig.BranchType(parentBranch)
+
+	childBranches := validatedConfig.NormalConfig.Lineage.Children(initialBranch, validatedConfig.NormalConfig.Order)
+	proposalsOfChildBranches := ship.LoadProposalsOfChildBranches(ship.LoadProposalsOfChildBranchesArgs{
```
Comment (kevgo) [inline internal/cmd/merge.go:295]: Great idea to reuse this function here!

File: internal/cmd/merge.go (hunk 1 above)
Comment (kevgo) [reply internal/cmd/merge.go:344]: Thanks for this background! Can you please add a comment that explains this, so that in future changes this important finding will be remembered?

Comment (yaadata) [reply internal/cmd/merge.go:344]: https://github.com/git-town/git-town/pull/5756/commits/3e0312e963a2d4541beb3fbffd08f6196d4637c5
