### PR TITLE
fix branch hierarchy verification step

### LINKED ISSUE #1619: "Git Town is now aware of this branch hierarchy" passes if entries in the table are missing

### PR DESCRIPTION
**Pull request by charlierudolph**
resolves #1619 

With this change and removing an entry from one test:

Screen Shot 2020-07-26 at 11 51 42 AM

### CODE REVIEW

File: test/steps.go [hunk 1]
```diff
@@ -104,11 +105,16 @@ func Steps(suite *godog.Suite, state *ScenarioState) {
...
-			state.gitEnv.DevRepo.Config.Reload()
-			parentBranch := state.gitEnv.DevRepo.Config.GetParentBranch(branch)
-			table.AddRow(branch, parentBranch)
+		state.gitEnv.DevRepo.Config.Reload()
+		// Table sorted by child branch name
+		parentBranchMap := state.gitEnv.DevRepo.Config.GetParentBranchMap() 
+		childBranches := make([]string, 0, len(parentBranchMap))
+		for child := range parentBranchMap {
+			childBranches = append(childBranches, child)
+		}
```
Comment (kevgo) [inline test/steps.go:114]: Can this be simplified to:

```suggestion
		childBranches = append(childBranches, parentBranchMap...)
```

Comment (charlierudolph) [reply test/steps.go:114]: Doesn't appear so.

Get the error:
```
test/steps.go:112:25: cannot use parentBranchMap (type map[string]string) as type []string in append
```

Was thinking if that was possible why that isn't used as the defacto way to get a map's keys
