### PR TITLE
fix: render proposal breadcrumbs with forge-specific references

### LINKED ISSUE #6071: Add Merge Request title breadcrumbs for gitlab
### Your message to us

Unlike GitHub, GitLab doesn’t show the merge request title when mentioning the number itself. It would be great to add the name of the merge request as text.

### PR DESCRIPTION
**Pull request by yaadata**
Closes #6071 

### Context 
Issue showed that proposal breadcrumb rendering was too generic: non-current entries were emitted as raw URLs, which missed forge-specific reference formats that render better inline metadata on hosts like GitLab.

This change moves breadcrumb reference rendering behind the forge connector layer. Each connector now provides its own proposal reference format, while lineage rendering keeps current-branch highlighting behavior unchanged and falls back deterministically when no forge-specific shorthand is available.

### What changed
- add connector-level proposal reference behavior in `internal/forge`
- update proposal lineage rendering to use connector-provided references instead of hardcoded URLs for non-current proposal nodes
- keep the current branch rendered as the emphasized title/branch name with `:point_left:` unchanged
- add deterministic fallback behavior for connectors or proposals that do not have a usable forge-specific shorthand
- add unit coverage for connector-specific reference rendering and lineage rendering behavior
- add end-to-end coverage for sync breadcrumb body updates across multiple proposals for:
  - GitHub
  - Forgejo
  - GitLab
  
### References

- GitHub autolinked refs:
  https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls
- GitLab Markdown refs: https://docs.gitlab.com/user/markdown/
- Gitea Markdown refs: https://docs.gitea.com/1.24/usage/markdown
- Forgejo linked refs: https://forgejo.org/docs/v14.0/user/linked-references/
- Bitbucket Data Center markdown guide:
  https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html
- Bitbucket Cloud markup comments:
  https://support.atlassian.com/bitbucket-cloud/docs/markup-comments/
- Azure DevOps markdown guidance:
  https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance

### CODE REVIEW

File: internal/forge/forgedomain/proposal_reference.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+		return "[" + title + "](" + proposal.URL + ")"
+	case proposal.URL != "":
+		return proposal.URL
+	case title != "":
+		return title
+	case proposal.Number.Int() > 0:
+		return "#" + proposal.Number.String()
+	default:
+		return ""
+	}
```
Comment (kevgo) [inline internal/forge/forgedomain/proposal_reference.go:21]: Suggestion to improve readability a bit. Feel free to adopt or reject based on how you feel about it.

```suggestion
	title := proposal.Title.String()
	hasTitle := title != ""
	hasURL := proposal.URL != ""
	hasNumber := proposal.Number.Int() > 0
	switch {
	case hasTitle && hasURL:
		return "[" + title + "](" + proposal.URL + ")"
	case hasURL:
		return proposal.URL
	case hasTitle:
		return title
	case hasNumber:
		return "#" + proposal.Number.String()
	default:
		return ""
	}
```

**Review by kevgo — APPROVED** [review]
Really good change, your best PR so far! I only have one (optional) readability improvement. Feel free to merge after deciding whether to adopt it. Thanks so much for this!

**Comment by tippfehlr** [comment]
thanks for doing this!

**Comment by kevgo** [comment]
This is now available in [Git Town 23.0](https://github.com/git-town/git-town/releases/tag/v23.0.0).
