### PR TITLE
fix author not being set properly

### LINKED ISSUE #1681: Wrong git ship commit author even I select another
I select the author of PR in the selection prompt during the `git ship` command but this selection is dropped and commit created by my authorship. I suspect git configuration for this project: I have overridden email in the local `.git/config` file (The name is not changed).

Maybe this is correct behavior, and local configuration precedes selection, can you clarify this point? 

Git Town v7.6.0 (2021/11/24)

### PR DESCRIPTION
**Pull request by charlierudolph**
resolves #1681

### CODE REVIEW

File: src/git/runner.go [hunk 1]
```diff
@@ -180,27 +180,16 @@ func (r *Runner) CommitStagedChanges(message string) error {
 	return nil
 }
 
-// CommitWithMessageAndAuthor .
-func (r *Runner) CommitWithMessageAndAuthor(message, author string) error {
-	_, err := r.Run("git", "commit", "-m", message, "--author", author)
-	if err != nil {
-		return fmt.Errorf("cannot commit with message %q and author %q: %w", message, author, err)
+// Commit commits staged changes with an optional message and author .
```
Comment (kevgo) [inline src/git/runner.go:183]: Remove the space before the period.

Comment (kevgo) [reply src/git/runner.go:183]: Suggestion to avoid stuttering:

```suggestion
// Commit performs a commit of the staged changes with an optional custom message and author.
```

File: src/git/runner.go [hunk 2]
```diff
@@ -180,27 +180,16 @@ func (r *Runner) CommitStagedChanges(message string) error {
...
+func (r *Runner) Commit(message, author string) error {
+	commitArgs := []string{"commit"}
```
Comment (kevgo) [inline src/git/runner.go:185]: This variable seems to contain the arguments for `git`. Call it `gitArgs`?

**Review by kevgo — APPROVED** [review]
Thanks for this excellent bugfix!

**Comment by kevgo** [comment]
I'm doing a ton of large-scale code repair. To avoid merge conflicts, I'm merging this in for now.
